version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: smartcalendar-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartcalendar
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  calendar-app:
    container_name: smartcalendar-app
    build:
      context: ./backend/calendar
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smartcalendar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
